name: nightly

on: [push]

jobs:
  ubuntu-aot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: 'preview'
      - name: Install Ubuntu dependencies
        run: sudo apt-get install -y clang zlib1g-dev libkrb5-dev
      - name: Restore JanD
        run: dotnet restore JanD -r linux-x64
      - name: Publish JanD
        run: dotnet publish JanD -c release -r linux-x64 -o ./artifacts/JanD -p:VersionSuffix=nightly-linux-x64-aot-$(git rev-parse --short HEAD)
      - name: Strippping
        run: strip ./artifacts/JanD/JanD
      - name: Move file
        run: mv ./artifacts/JanD/JanD ./artifacts/JanD/jand-linux-x64-aot
      - name: Upload JanD
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          name: jand-linux-x64
          path: ./artifacts/JanD/jand-linux-x64-aot
          if-no-files-found: error
      - name: Release
        with:
          draft: true
          files: ./artifacts/JanD/jand-linux-x64-aot
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
  contained:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [linux-arm, linux-arm64, osx-x64, osx-arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: 'preview'
      - name: Restore JanD
        run: dotnet restore JanD -r ${{ matrix.rid }} -p:NoNativeAOTPublish=h
      - name: Publish JanD
        run: dotnet publish JanD -c release -r ${{ matrix.rid }} -o ./artifacts/JanD -p:VersionSuffix=nightly-${{ matrix.rid }}-contained-$(git rev-parse --short HEAD) -p:NoNativeAOTPublish=h --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true
      - name: Move file
        run: mv ./artifacts/JanD/JanD ./artifacts/JanD/jand-${{ matrix.rid }}-contained
      - name: Upload JanD
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          name: jand-${{ matrix.rid }}-contained
          path: ./artifacts/JanD/jand-${{ matrix.rid }}-contained
          if-no-files-found: error
      - name: Release
        with:
          draft: true
          files: ./artifacts/JanD/jand-${{ matrix.rid }}-contained
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
  osx-aot:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: 'preview'
      - name: Restore JanD
        run: dotnet restore JanD -r osx-x64
      - name: Publish JanD
        run: dotnet publish JanD -c release -r osx-x64 -o ./artifacts/JanD -p:VersionSuffix=nightly-osx-x64-aot-$(git rev-parse --short HEAD)
      - name: Move file
        run: mv ./artifacts/JanD/JanD ./artifacts/JanD/jand-osx-x64-aot
      - name: Upload JanD
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          name: jand-osx-x64
          path: ./artifacts/JanD/jand-osx-x64-aot
          if-no-files-found: error
      - name: Release
        with:
          draft: true
          files: ./artifacts/JanD/jand-osx-x64-aot
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
  windows-aot:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: 'preview'
      - name: Restore JanD
        run: dotnet restore JanD -r win-x64
      - name: Publish JanD
        run: dotnet publish JanD -c release -r win-x64 -o ./artifacts/JanD -p:VersionSuffix=nightly-windows-x64-aot-$(git rev-parse --short HEAD)
      - name: Move file
        run: mv ./artifacts/JanD/JanD.exe ./artifacts/JanD/jand-windows-x64-aot.exe
      - name: Upload JanD
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          name: jand-windows-x64.exe
          path: ./artifacts/JanD/jand-windows-x64-aot.exe
          if-no-files-found: error
      - name: Release
        with:
          draft: true
          files: ./artifacts/JanD/jand-windows-x64-aot.exe
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')